export const ACTIVITY_PRODUCT_LIST_SET = 'ACTIVITY_PRODUCT_LIST_SET'
export const ACTIVITY_PRODUCT_LIST_CONCAT = 'ACTIVITY_PRODUCT_LIST_CONCAT'
export const USERS_INFO_SET = 'USERS_INFO_SET'
export const USERS_INFO_CLEAR = 'USERS_INFO_CLEAR'

// 新的请求
export const LOADING_NEW = 'LOADING_COUNT'
// 请求完成
export const LOADING_COMPLETE = 'LOADING_COMPLETE'
